### ISSUE TITLE
auto-sklearn version issue

### ISSUE THREAD

**Issue by qqspm** [jf-lab/cnmfe-reviewer#1]
Have to install the auto-sklearn manually but got an error: “cnmfereview 0.1 has requirement auto-sklearn>0.6.0, but you'll have auto-sklearn 0.6.0 which is incompatible.” 
I could not find an newer version than 0.6.0.

**Comment by linamnt** [comment]
Hi @qqspm, I've updated the setup.py to be >=0.6.0 instead. Let me know if that doesn't work.
